# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977bcbe4c34e88c3699110eae865f539d07f4e6c6a89d005ff5f9061e1b420df4b851868ab2c5c70a90fc450698fb8170eaabd0a026a4a4c7b647250ab37a3f4

test:
  secret_key_base: 4f5da1f665bc2adea58a10e71e64f0bb4be86caa6988598e30040f88f0ef1518acdfd6df88c18f07ab60d4af1cacaf0a324b2b807a2dce79e9266e4a426a3558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
